-- Add foreign key constraints
ALTER TABLE "BOOKINGS" ADD FOREIGN KEY ("CUSTOMER_ID")
    REFERENCES "CUSTOMERS" ("CUSTOMER_ID") ENABLE;

ALTER TABLE "BOOKINGS" ADD FOREIGN KEY ("MUSEUM_ID")
    REFERENCES "MUSEUM" ("MUSEUM_ID") ENABLE;

ALTER TABLE "BOOKINGS_DENORMALIZE" ADD FOREIGN KEY ("MUSEUM_ID")
    REFERENCES "MUSEUM" ("MUSEUM_ID") ENABLE;

ALTER TABLE "BOOKINGS_DENORMALIZE" ADD FOREIGN KEY ("BOOKING_ID")
    REFERENCES "BOOKINGS" ("BOOKING_ID") ENABLE;

ALTER TABLE "BOOKINGS_DENORMALIZE" ADD FOREIGN KEY ("CUSTOMER_ID")
    REFERENCES "CUSTOMERS" ("CUSTOMER_ID") ENABLE;


