-- Create tables
CREATE TABLE "BOOKINGS" (
    "BOOKING_ID" NUMBER(4,0) NOT NULL ENABLE,
    "BOOKING_DATE" DATE,
    "BOOKING_TYPE" VARCHAR2(54),
    "TITLE" VARCHAR2(80),
    "CUSTOMER_ID" NUMBER(4,0) NOT NULL ENABLE,
    "MUSEUM_ID" NUMBER(4,0) NOT NULL ENABLE,
    PRIMARY KEY ("BOOKING_ID") USING INDEX ENABLE
);

CREATE TABLE "BOOKINGS_DENORMALIZE" (
    "MUSEUM_ID" NUMBER(5,0) NOT NULL ENABLE,
    "BOOKING_ID" NUMBER(5,0) NOT NULL ENABLE,
    "CUSTOMER_ID" NUMBER(5,0) NOT NULL ENABLE,
    "BOOKING_TITLE" VARCHAR2(50),
    "BOOKING_TYPE" VARCHAR2(50),
    "BOOKING_DATE" DATE,
    "MUSEUM_NAME" VARCHAR2(50),
    CONSTRAINT "PK_MUSEUM_BOOKINGS_CUSTOMERS" PRIMARY KEY ("MUSEUM_ID", "BOOKING_ID", "CUSTOMER_ID") USING INDEX ENABLE
);

CREATE TABLE "CUSTOMERS" (
    "CUSTOMER_ID" NUMBER(4,0) NOT NULL ENABLE,
    "FIRST_NAME" VARCHAR2(50),
    "LAST_NAME" VARCHAR2(50),
    "CUSTOMER_AGE" NUMBER(*,0),
    "CUSTOMER_E_MAIL" VARCHAR2(125),
    PRIMARY KEY ("CUSTOMER_ID") USING INDEX ENABLE
);


