-- Insert data into CUSTOMERS
INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, CUSTOMER_AGE, CUSTOMER_E_MAIL)
VALUES
(1, 'PETER', 'SMITH', 20, 'PETERSON@GMAIL.COM'),
(2, 'JOHN', 'CLARKE', 68, 'CLARK123@YAHOO.COM'),
(3, 'REBECCA', 'CLEMENTS', 74, 'REBECCA@YAHOO.COM'),
(4, 'CRAIG', 'HAMMER', 2, 'CRAIG_HAMMER@YAHOO.COM'),
(5, 'NEIL', 'PRICE', 2, 'PRICEY_BABY@GMAIL.COM'),
(6, 'SAMUEL', 'STEVENSON', 11, 'SAMUEL1994@GMAIL.COM'),
(7, 'AARON', 'LEWIS', 9, 'AARON77@GMAIL.COM'),
(8, 'ADAM', 'DAVIES', 23, 'ADAM@GMAIL.COM'),
(10, 'ADRIAN', 'HEATH', 35, 'ADRIAN@GMAIL.COM');
